### ISSUE TITLE
Написать XML-комментарии для всех классов, методов и свойств для документации.

### ISSUE THREAD

**Issue by DenisBabarykin** [iu7-12-dbg/t06-lab01#3]

**Comment by gashetinin** [comment]
ок, сделаю (если не успею до конца сегодня, то за завтра точно завершу)

**Comment by DenisBabarykin** [comment]
Разумеется, комментарии на русском языке, пожалуйста)

**Comment by gashetinin** [comment]
Комментарии сделаны + добавил 1 тест: вычисление расстояние Левенштейна между одинаковыми строками (равно 0)
